[package]
name = "saltwater"
version = "0.1.0"
authors = ["Misha Kononov <misha.kononov@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.13"